# Enable C++ support
language: cpp

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-6
    - compiler: clang


before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install --user hfcca
  - pip install --user cpplint

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - gcc-6
      - g++-6
      - doxygen
      - valgrind
      - cppcheck

script:
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1
  - ctest -j 10 -T memcheck
  - make review
